import 'dart:io' show File;

import 'package:flutter/material.dart';

import '../design/tokens.dart';

/// Domain model for the 還車拍照 flow (Figma group 986:1342).
///
/// The Figma board lays the flow out as six numbered scenarios. Everything the
/// screens need in order to play one of them back — the shot list, what the
/// on-device check reports, whether the driver is stopped, and which push
/// arrives afterwards — is declared here, so the widgets stay presentational
/// and the demo can be re-pointed at a real detector later by swapping
/// [ReturnScenario.analysis] for live data.

const String _kAssetRoot = 'assets/images/return';

// ---------------------------------------------------------------------------
// Shot list
// ---------------------------------------------------------------------------

/// One frame the driver has to hand in, in strip order (Figma 拍照流程).
///
/// Seven slots, not five: the board opens on the 加油卡/停車卡 shot, takes both
/// cabin rows, and only then walks the four body corners. The order here *is*
/// the order of the strip and of the flow, so nothing else has to restate it.
///
/// The four corners go 左前 → 右前 → 右後 → 左後, which is one lap of the car:
/// across the nose, down the passenger side, across the tail. They used to go
/// 右前 → 左前 → 右後 → 左後, and that is two laps — the driver crossed the
/// front, came back, crossed to the rear-right, and crossed again. Four shots
/// is few enough that the wasted walking is the whole difference between a
/// return that feels like a circuit and one that feels like errands.
/// What the viewfinder draws over the live frame for one slot.
enum GuideStyle {
  /// Nothing. The driver frames the shot themselves.
  ///
  /// The two cabin rows. There is no repeatable angle to ask for inside a car
  /// — the phone is a hand's width from the seat back and every driver's
  /// posture puts it somewhere different — so an outline there is a shape
  /// nobody can match, and being unable to match it is the only thing it
  /// communicates. The strip tile still shows the 示意圖: saying *which* seats
  /// to point at is useful, drawing where their edges must land is not.
  none,

  /// The car render, tinted by [AimState]. The four body corners.
  silhouette,

  /// The 遮陽板 card holder: an outer frame with the two card pockets marked.
  ///
  /// Drawn rather than an asset — it is three rounded rectangles and two
  /// labels, which vector code renders crisply at any size and a PNG does not.
  cardPouch,
}

enum CaptureSpot {
  fuelCard(
    label: '加油卡/停車卡',
    screenTitle: '加油卡/停車卡',
    instruction: '於駕駛座上方的遮陽板',
    art: 'fuel_card',
    // The 遮陽板 card holder itself, not a card. Measured off the pouch: two
    // card pockets either side of the branded centre panel.
    guideAspect: 1.70,
    isCorner: false,
    guide: GuideStyle.cardPouch,
  ),
  interiorFront(
    label: '前座',
    screenTitle: '車內裝(前座)',
    instruction: '請拍攝前座照片',
    art: 'indoor_front',
    guideAspect: 1.6000,
    isCorner: false,
    guide: GuideStyle.none,
  ),
  interiorRear(
    label: '後座',
    screenTitle: '車內裝(後座)',
    instruction: '請拍攝後座照片',
    art: 'indoor_back',
    guideAspect: 1.5335,
    isCorner: false,
    guide: GuideStyle.none,
  ),
  frontLeft(
    label: '左前',
    art: 'left_front',
    guideAspect: 1.8804,
    guideBleed: 0.16,
  ),
  frontRight(
    label: '右前',
    art: 'right_front',
    guideAspect: 1.8955,
    guideBleed: -0.16,
  ),
  rearRight(
    label: '右後',
    art: 'right_back',
    guideAspect: 1.8054,
    guideBleed: 0.16,
  ),
  rearLeft(
    label: '左後',
    art: 'left_back',
    guideAspect: 1.8020,
    guideBleed: -0.16,
  );

  const CaptureSpot({
    required this.label,
    required this.art,
    required this.guideAspect,
    this.screenTitle = '車身拍照',
    this.instruction = '請拍攝車輛四角（含車牌）',
    this.isCorner = true,
    this.guide = GuideStyle.silhouette,
    this.guideBleed = 0,
  });

  /// Short name used inside the copy ("**右後** 照片有不明亮點…").
  final String label;

  /// Header title. The four body shots share one 車身拍照 task; the other three
  /// each name themselves.
  final String screenTitle;

  /// Sub-header under the title.
  final String instruction;

  /// Base name of the artwork this slot owns — strip tile and the three guide
  /// layers — all generated by `tool/gen_slot_assets.py` from the 1440px
  /// masters in `tool/slot_paint/`.
  final String art;

  /// Width ÷ height of the shape drawn over the frame. For a
  /// [GuideStyle.silhouette] slot it is measured off the source alpha by
  /// `gen_slot_assets.py`, so the viewfinder can lay the guide out without
  /// decoding the image first; for [GuideStyle.cardPouch] it is the pouch's
  /// own proportions. Unused when [guide] is [GuideStyle.none].
  final double guideAspect;

  /// True for the four body corners — the only slots the car detector, and so
  /// the guide-overlap check, can say anything about.
  final bool isCorner;

  /// What, if anything, is drawn over the live frame for this slot.
  final GuideStyle guide;

  /// A standing loosening of the aim thresholds for this slot, 0…1.
  ///
  /// The three interior shots get 0.35. The thresholds' defaults are tuned for
  /// a whole car at arm's length in daylight; the 遮陽板 and the two cabin rows
  /// are close-ups of dark surfaces under a roof, often with the driver's own
  /// shadow across them, and the blur floor and exposure ceilings that are
  /// right outdoors are simply not reachable in there. A slot that can never
  /// go green is a slot the driver fights until they abandon the return.
  double get aimSlack => isCorner ? 0 : 0.35;

  /// How far the silhouette is allowed to run off one edge of the screen, as a
  /// fraction of its own width. Negative bleeds off the **left** edge, positive
  /// off the right; 0 keeps the whole shape on screen.
  ///
  /// A guide that fits entirely on screen asks the driver to frame the *whole
  /// car*, which puts them ten paces back and makes the corner they are
  /// actually documenting — bumper, headlight, wheel arch — a handful of
  /// pixels wide. Letting the far end of the car run out of frame is what buys
  /// those pixels: the near corner grows to fill the screen, and the features
  /// the driver aligns against (front bumper line, A-pillar, wheel arch) are
  /// the ones that stay in it.
  ///
  /// So the bleed is always on the side **away from the corner being shot**,
  /// and it alternates down the strip because the walk does. In the 右前 render
  /// the nose sits on the right of the frame, so the tail is what runs off the
  /// left; 左前 is its mirror. The two rear shots follow the same rule one lap
  /// later — 右後 bleeds off the right and keeps its left margin, 左後 the
  /// mirror of that — which is what makes their outlines as large as the front
  /// pair's instead of a shrunken whole car floating in the middle of the
  /// frame.
  final double guideBleed;

  /// Strip indicator shown while the slot is still empty. 288×288 — 4x the
  /// 72pt tile, so it stays sharp on a 3x screen. It used to be the design
  /// repo's own 72×72 export, which was exactly one logical pixel per point
  /// and visibly mushy on a real phone.
  String get slotIcon => '$_kAssetRoot/slots/$art.png';

  /// Alignment silhouette laid over the live frame. White with a soft alpha
  /// edge, tinted per [AimState] at paint time.
  String get guideAsset => '$_kAssetRoot/guide/$art.png';

  /// The 示意圖 itself — the car render, drawn semi-transparent over the live
  /// frame underneath [guideEdgeAsset].
  ///
  /// A flat tinted silhouette can only say "the car goes roughly here". What
  /// the driver is being asked for is a *repeatable* angle, and repeatable
  /// means lining real features up against drawn ones: the bumper's lower
  /// edge, the A-pillar, where the wheel arch meets the sill. Those only exist
  /// in the render, so the render is what goes on screen.
  String get guideArtAsset => '$_kAssetRoot/guide/${art}_art.png';

  /// The same silhouette as an outline, drawn over [guideAsset]. Registered
  /// pixel for pixel with it, so both go in the same rect.
  String get guideEdgeAsset => '$_kAssetRoot/guide/${art}_edge.png';

  /// Live view behind the viewfinder chrome. A still stands in for the camera
  /// feed on a device that has none.
  String get viewfinderAsset => isCorner
      ? '$_kAssetRoot/camera_scene.png'
      : '$_kAssetRoot/shot_interior.jpg';

  /// Stand-in for the strip when a slot was "shot" without a camera behind it —
  /// a desktop, the web, a widget test. With a camera the tile shows the frame
  /// that was actually taken and this is never reached.
  String get shotAsset => isCorner
      ? '$_kAssetRoot/shot_scene.jpg'
      : '$_kAssetRoot/shot_interior.jpg';
}

/// What the on-device check makes of the current frame.
///
/// This is the 防亂拍 signal: it is evaluated live while the viewfinder is
/// open, never after the fact. The shutter stays armed in every state — an
/// off-target frame is warned about, not blocked (Figma scenario ⑥).
enum AimState {
  /// 未對準 — nothing recognisable in frame, or the car is nowhere near the
  /// outline. Grey.
  off(
    '未對準',
    AppColor.aimOff,
    AppColor.guideOff,
    AppColor.guideOffEdge,
    '對齊輪廓線',
  ),

  /// 接近 — the car is on the outline but at the wrong distance (or the frame
  /// is soft or badly lit). Amber, and the hint always says which way to walk.
  near('接近', AppColor.aimNear, AppColor.aimNear, AppColor.aimNear, '再靠近一點'),

  /// 已對準 — good enough to submit.
  locked(
    '已對準',
    AppColor.aimLocked,
    AppColor.aimLocked,
    AppColor.aimLocked,
    null,
  ),

  /// 車輛不符 — a plate was read, repeatedly and clearly, and it is not the car
  /// on the rental agreement. Red.
  ///
  /// Its own state rather than a flavour of [off] because it is the one verdict
  /// the driver cannot answer by moving the phone. Every other state means
  /// "adjust the shot"; this one means "you are standing at the wrong car", and
  /// a grey 未對準 badge would send them shuffling back and forth in front of
  /// somebody else's bumper. It still does not lock the shutter — see
  /// [AimVerdict.isAcceptable].
  wrongCar(
    '車輛不符',
    AppColor.aimWrongCar,
    AppColor.aimWrongCar,
    AppColor.aimWrongCar,
    '這不是你租的車',
  );

  const AimState(
    this.label,
    this.color,
    this.guideColor,
    this.guideEdgeColor,
    this.hint,
  );

  final String label;

  /// Badge fill under the header.
  final Color color;

  /// Fill of the alignment silhouette, and the tint of its outline.
  /// **灰 = 未對準・黃 = 距離不對・綠 = 已對準**, which is the only thing on screen
  /// that reads at arm's length while the driver is moving.
  final Color guideColor;

  /// Stroke around that silhouette. Same colour as the fill once the check is
  /// saying something (amber, green); a darker grey while it is not, because
  /// 未對準 is the one state that has to stand off a bright wall.
  final Color guideEdgeColor;

  /// Centre pill copy; null once the frame is good, when the pill disappears.
  final String? hint;

  bool get isAcceptable => this == AimState.locked;
}

// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------

/// One row of the 還車分析 page — a title, a bar, and a verdict line.
class AnalysisCheck {
  const AnalysisCheck({
    required this.title,
    required this.pendingLabel,
    required this.resultLabel,
    required this.ok,
    this.ratio = 1.0,
  });

  final String title;

  /// Shown while the bar is still filling.
  final String pendingLabel;

  /// Shown once the bar settles.
  final String resultLabel;

  /// Drives the colour of the settled bar and its verdict line.
  final bool ok;

  /// How far the settled bar fills. A failed check stops short of the end.
  final double ratio;

  Color get resultColor => ok ? AppColor.successText : AppColor.aimNear;
}

/// What kind of problem a [ReturnFinding] is.
///
/// Not a severity. The three are different questions with different answers —
/// a frame nobody can read is fixed by standing somewhere else, rubbish is
/// fixed by picking it up, a missing card is fixed by walking back to the
/// office — and the 需處理 page picks its copy off this rather than off the
/// slot, which cannot tell 「後座有垃圾」 from 「後座拍糊了」.
enum FindingKind {
  /// L1 could not read the photo.
  unreadable,

  /// The cabin has rubbish in it.
  trash,

  /// The 遮陽板 card pouch is missing a card.
  missingCard,
}

/// One problem the 需處理 page reports, drawn as its own card.
///
/// **Every problem is reported, not the worst one.** The page used to pick a
/// single issue and ask about it: with two bad photos the second one was
/// invisible until the first had been redone and the analysis had run again,
/// so a driver with two problems was told about them one at a time, in two
/// round trips, with no way to know a second was coming. Ranking answers
/// "which is worst" — a question nobody asked — and hides the answer to "what
/// is wrong", which is the only one they have.
class ReturnFinding {
  const ReturnFinding({
    required this.title,
    required this.reason,
    required this.kind,
    this.spot,
    this.photo,
  });

  /// Which of the three problems this is. Drives the page's headline, its
  /// advisory note and the label on its retake button.
  final FindingKind kind;

  /// 「停車卡不通過」/「右後不通過」— what the card is about.
  final String title;

  /// L1's own words for why. Rendered as prose beside the photo, so it wraps
  /// and the card grows; nothing here is length-limited.
  final String reason;

  /// The slot this is about, when it is about one. Drives the fallback
  /// thumbnail for a scripted run that has no real photo behind it.
  final CaptureSpot? spot;

  /// The frame the driver actually took. Null on a scripted run.
  final File? photo;

  /// The same finding with the driver's own frame attached.
  ///
  /// A scripted scenario is a `const`, so it cannot carry a [File] and its
  /// cards fall back to the slot's 示意圖. That fallback is right when there is
  /// no photo — and wrong here, because there is one: the driver shot that slot
  /// a minute ago and the card is *about* that shot. The flow is the only thing
  /// holding both, so it pairs them up on the way to the page.
  ///
  /// A finding that already has a photo keeps it. Live findings arrive with
  /// L1's own copy of the frame and it is the one L1 was looking at.
  ReturnFinding withPhoto(File? file) {
    if (file == null || photo != null) return this;
    return ReturnFinding(
      title: title,
      reason: reason,
      kind: kind,
      spot: spot,
      photo: file,
    );
  }
}

/// The verdict the 還車分析 page renders.
class ReturnAnalysis {
  const ReturnAnalysis({
    required this.photo,
    required this.cabin,
    this.findings = const [],
  });

  final AnalysisCheck photo;
  final AnalysisCheck cabin;

  /// Everything wrong with this return, in slot order. Empty is the good case.
  final List<ReturnFinding> findings;

  bool get allClear => findings.isEmpty;

  /// The primary button under the settled bars.
  ///
  /// It forks, because the page after it does. A clean return goes straight to
  /// the release page and the button says so; a return with problems has a
  /// page of its own to go to, and 前往下一步 is the one label that does not
  /// promise which way that page ends.
  String get continueLabel => allClear ? '繼續還車' : '前往下一步';

  static const _photoOk = AnalysisCheck(
    title: '照片可判讀性',
    pendingLabel: '正在處理中',
    resultLabel: '7 張照片皆可判讀',
    ok: true,
  );

  static const _cabinOk = AnalysisCheck(
    title: '車內整潔度',
    pendingLabel: '正在處理中',
    resultLabel: '車內整潔，無需清理',
    ok: true,
  );

  /// 情境①④⑤ — everything passes; any damage verdict is deliberately absent
  /// from this page and handled off-screen.
  static const clear = ReturnAnalysis(photo: _photoOk, cabin: _cabinOk);

  /// 情境② — one frame is unreadable.
  static const glare = ReturnAnalysis(
    photo: AnalysisCheck(
      title: '照片可判讀性',
      pendingLabel: '正在處理中',
      resultLabel: '右後不通過',
      ok: false,
      ratio: 0.857,
    ),
    cabin: _cabinOk,
    findings: [
      ReturnFinding(
        title: '右後不通過',
        reason: '照片有不明亮點（局部反光），車身漆面被洗白，影響判讀。請換一個角度避開光源後補拍一張。',
        kind: FindingKind.unreadable,
        spot: CaptureSpot.rearRight,
      ),
    ],
  );

  /// 情境⑦ — two problems at once, which is the case the 需處理 page exists
  /// for. One bad photo and one dirty cabin is the ordinary way a return goes
  /// wrong twice, and it is the only way to see the difference the page makes:
  /// both are named up front and one 重拍 re-opens both slots, where a page per
  /// problem would send the driver round the car twice.
  static const multiple = ReturnAnalysis(
    photo: AnalysisCheck(
      title: '照片可判讀性',
      pendingLabel: '正在處理中',
      resultLabel: '右後不通過',
      ok: false,
      ratio: 0.857,
    ),
    cabin: AnalysisCheck(
      title: '車內整潔度',
      pendingLabel: '正在處理中',
      resultLabel: '後座：飲料杯、紙袋',
      ok: false,
      ratio: 0.78,
    ),
    findings: [
      ReturnFinding(
        title: '後座有垃圾',
        reason: '腳踏墊處有飲料杯與紙袋。請將垃圾帶走後再完成還車，順手帶走可維持你的優良駕駛等級。',
        kind: FindingKind.trash,
        spot: CaptureSpot.interiorRear,
      ),
      ReturnFinding(
        title: '右後不通過',
        reason: '照片有不明亮點（局部反光），車身漆面被洗白，影響判讀。請換一個角度避開光源後補拍一張。',
        kind: FindingKind.unreadable,
        spot: CaptureSpot.rearRight,
      ),
    ],
  );

  /// 情境③ — the only thing the driver is ever asked to fix on the spot.
  static const trash = ReturnAnalysis(
    photo: _photoOk,
    cabin: AnalysisCheck(
      title: '車內整潔度',
      pendingLabel: '正在處理中',
      resultLabel: '後座：飲料杯、紙袋',
      ok: false,
      ratio: 0.78,
    ),
    findings: [
      ReturnFinding(
        title: '後座有垃圾',
        reason: '腳踏墊處有飲料杯與紙袋。請將垃圾帶走後再完成還車，順手帶走可維持你的優良駕駛等級。',
        kind: FindingKind.trash,
        spot: CaptureSpot.interiorRear,
      ),
    ],
  );
}

// ---------------------------------------------------------------------------
// Follow-up notifications
// ---------------------------------------------------------------------------

/// A push that lands after the driver has already walked away.
///
/// The Figma boards show these on a lock screen an hour after the return, and
/// that is exactly where they land — the notification tray, nowhere else. The
/// point being demonstrated is the timing: nothing about damage is said at the
/// counter, because the layers that can say it honestly take minutes.
class ReturnNotice {
  const ReturnNotice({required this.body, required this.delay});

  final String body;

  /// How long after the return the notification is posted. The boards' 「1h
  /// ago」 is compressed to seconds so the demo can be watched; the tray writes
  /// its own timestamp either way.
  final Duration delay;
}

/// The push that lands when the back office never answered.
///
/// A return whose L1/L2/L3 calls never reached anything still has to end the
/// way every other return ends: the driver walked away expecting 「結果將以通知
/// 告知」, and silence is the one outcome that reads as the app having dropped
/// their return on the floor. So the offline path says the same thing the
/// all-clear path says — the photos were readable, the cabin was clean, there
/// is nothing to pay — and the tap opens the same 訂單明細.
///
/// This is a demo affordance, stated plainly: with no service behind it the
/// app cannot know any of that. It is the right default anyway, because the
/// alternative is accusing someone on the strength of a failed HTTP call.
const offlineReturnNotice = ReturnNotice(
  body: '本次還車分析已完成：照片皆可判讀、車內整潔，您無需負擔任何費用。感謝愛惜車輛✨',
  delay: Duration(seconds: 3),
);

// ---------------------------------------------------------------------------
// Scenarios
// ---------------------------------------------------------------------------

/// The six columns of the Figma board, in board order — plus the live one.
enum ReturnScenario {
  /// ⓪ 真實檢測 — no script at all: the phone's camera drives L0, the photos go
  /// to L1, and L2/L3 run once the driver leaves. Selected automatically when
  /// the `api/` service answers, so a dead network falls back to the board
  /// rather than to a broken demo.
  live(number: '⓪', title: '真實 AI 檢測', caption: '相機跑 L0，照片送 L1，離開後跑 L2／L3。'),

  /// ① 一切順利（最常見）— 全程放行
  allClear(number: '①', title: '一切順利', caption: '拍照全達標，分析全過，直接放行，事後零通知。'),

  /// ② 局部反光・需重拍 — 唯一會擋下的照片問題
  glare(number: '②', title: '有一張需要重拍', caption: '右後照片反光影響判讀，補拍一張後放行。'),

  /// ③ 車內偵測到垃圾（整潔度）— 唯一強制處理點
  trash(number: '③', title: '車內偵測到垃圾', caption: '可清理後重拍，或接受信用影響直接還車。'),

  /// ④ 紀錄外損傷・輕微 — 使用者全程無感
  minorDamage(
    number: '④',
    title: '輕微損傷（無感放行）',
    caption: '畫面與情境①相同，差異只在事後一則好消息。',
  ),

  /// ⑤ 紀錄外損傷・嚴重 — 當下放行・事後人工
  severeDamage(number: '⑤', title: '嚴重損傷（求償）', caption: '放行頁一字不提，求償由客服人工聯繫。'),

  /// ⑥ 亂拍・自負責任送出 — 還車不阻斷
  sloppy(number: '⑥', title: '亂拍・自負責任送出', caption: '快門永不鎖定，不合格照片可直接送出。'),

  /// ⑦ 兩個問題同時發生 — 需處理頁一次列完、一次重拍
  multiple(
    number: '⑦',
    title: '同時有兩個問題',
    caption: '後座有垃圾＋右後反光，一頁列完，一次重拍兩張。',
  );

  const ReturnScenario({
    required this.number,
    required this.title,
    required this.caption,
  });

  final String number;
  final String title;
  final String caption;

  /// What the 還車分析 page reports for this scenario.
  ReturnAnalysis get analysis => switch (this) {
    ReturnScenario.glare => ReturnAnalysis.glare,
    ReturnScenario.trash => ReturnAnalysis.trash,
    ReturnScenario.multiple => ReturnAnalysis.multiple,
    _ => ReturnAnalysis.clear,
  };

  /// Pushes that arrive after the driver has left.
  List<ReturnNotice> get notices => switch (this) {
    ReturnScenario.multiple => const [
      ReturnNotice(
        body: '已確認車內整潔、補拍照片可判讀，您的信用分數維持不變，感謝配合✨',
        delay: Duration(seconds: 3),
      ),
    ],
    ReturnScenario.trash => const [
      ReturnNotice(
        body: '已確認車內整潔，您的信用分數維持不變，感謝配合✨',
        delay: Duration(seconds: 3),
      ),
    ],
    ReturnScenario.minorDamage => const [
      ReturnNotice(
        body: '本次還車深度分析已完成，您無需負擔任何費用。感謝愛惜車輛，優良駕駛進度 +1',
        delay: Duration(seconds: 3),
      ),
    ],
    ReturnScenario.severeDamage => const [
      ReturnNotice(
        body: '本次還車偵測到需進一步確認之車況，客服人員複核中，將於 24 小時內與您聯繫。',
        delay: Duration(seconds: 3),
      ),
      ReturnNotice(
        body:
            '經人工複核，本次租用期間新增「後保險桿脫落」。求償金額 NT\$8,500。'
            '點此查看取車／還車比對照片 · 7 日內提出申訴',
        delay: Duration(seconds: 9),
      ),
    ],
    _ => const [],
  };

  /// 情境⑥ opens the viewfinder already off-target so the 判定未達標 panel is
  /// the first thing the demo shows.
  bool get startsMisaligned => this == ReturnScenario.sloppy;
}
